search_server

diff --git a/bin/index b/bin/index
--- a/bin/index
+++ b/bin/index
@@ -4,29 +4,40 @@ set -Eeuo pipefail
 set -x
 
 usage() {
-  echo "Usage: $0 (create|destroy|reset)"
+  echo "Usage: $0 (start|stop|status)"
 }
 if [ $# -ne 1 ]; then
   usage
   exit 1
 fi
 case $1 in
-  "create")
-    if [ -e var/search.sqlite3 ]
-    then
-      echo "Error: database already exists"
-      exit 0
+  "start")
+    mkdir -p var/log
+    rm -f var/log/index.log
+    INDEX_PATH="inverted_index_0.txt" flask --app index run --host 0.0.0.0 --port 9000 >> var/log/index.log 2>&1 &
+    INDEX_PATH="inverted_index_1.txt" flask --app index run --host 0.0.0.0 --port 9001 >> var/log/index.log 2>&1 &
+    INDEX_PATH="inverted_index_2.txt" flask --app index run --host 0.0.0.0 --port 9002 >> var/log/index.log 2>&1 &
+    ;;
+  "stop")
+    echo "stopping index server ..."
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9000" || true
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9001" || true
+    pkill -f "flask --app index run --host 0.0.0.0 --port 9002" || true
+    ;;
+  "status")
+    set +o pipefail
+    NPROCS=$(pgrep -f "flask --app index run --host 0.0.0.0 --port 900[0-2]" | wc -l)
+    set -o pipefail
+    if [ "$NPROCS" -eq 3 ]; then
+      echo "index server running"
+      exit
+    elif [ "$NPROCS" -eq 0 ]; then
+      echo "index server stopped"
+      exit 1
+    else
+      echo "index server error: found ${NPROCS} processes, expected 3"
+      exit 2
     fi
-    mkdir -p var/
-    sqlite3 var/search.sqlite3 < search_server/search/sql/search.sql
-    ;;
-  "destroy")
-    rm -rf var/search.sqlite3
-    ;;
-  "reset")
-    rm -f var/search.sqlite3
-    mkdir -p var/
-    sqlite3 var/search.sqlite3 < search_server/search/sql/search.sql
     ;;
   *)
     usage
